import { lazyWithRetry } from './utils/lazyWithRetry';

const lazy = lazyWithRetry;

export const AdminDashboard = lazy(() => import('./AdminDashboard'));
export const CustomersPage = lazy(() => import('./CustomersPage'));
export const TicketsPage = lazy(() => import('./TicketsPage'));
export const SalesPage = lazy(() => import('./SalesPage'));
export const LeadsPage = lazy(() => import('./LeadsPage'));
export const AnalyticsPage = lazy(() => import('./AnalyticsPage'));
export const FeedbackPage = lazy(() => import('./FeedbackPage'));
export const PerformancePage = lazy(() => import('./PerformancePage'));
export const StaffShopPage = lazy(() => import('./dashboards/StaffShopPage'));
export const KnowledgeBasePage = lazy(() => import('./KnowledgeBasePage'));
export const UserManagementPage = lazy(() => import('./UserManagementPage'));
export const RolePermissionsPage = lazy(() => import('./RolePermissionsPage'));
export const BillingPage = lazy(() => import('./BillingPage'));
export const ComplianceReportsPage = lazy(() => import('./ComplianceReportsPage'));
export const DataManagementPage = lazy(() => import('./DataManagementPage'));
export const SecurityAuditPage = lazy(() => import('./SecurityAuditPage'));
export const SystemConfigPage = lazy(() => import('./SystemConfigPage'));
export const SystemHealthPage = lazy(() => import('./SystemHealthPage'));
export const ProfilePage = lazy(() => import('./ProfilePage'));
export const ProductsManagementPage = lazy(() => import('./ProductsManagementPage'));
export const HotDealsManagementPage = lazy(() => import('./HotDealsManagementPage'));
export const HotDealsPage = lazy(() => import('./HotDealsPage'));
export const CustomerDashboard = lazy(() => import('./dashboards/CustomerDashboard'));
export const CustomerProductsPage = lazy(() => import('./dashboards/CustomerProductsPage'));
export const CustomerTicketsPage = lazy(() => import('./dashboards/CustomerTicketsPage'));
export const ContactSupportPage = lazy(() => import('./dashboards/ContactSupportPage'));
export const CustomerMessagesPage = lazy(() => import('./dashboards/CustomerMessagesPage'));
export const SalesPlaybookPage = lazy(() => import('./SalesPlaybookPage'));
export const SalesMessagesPage = lazy(() => import('./dashboards/SalesMessagesPage'));
export const ConversationMonitorPage = lazy(() => import('./dashboards/ConversationMonitorPage'));
export const CalendarPage = lazy(() => import('./dashboards/CalendarPage'));
export const LeavePage = lazy(() => import('./dashboards/LeavePage'));
export const BroadcastPage = lazy(() => import('./dashboards/BroadcastPage'));
export const ApprovalsPage = lazy(() => import('./dashboards/ApprovalsPage'));
export const SalesAgentDashboard = lazy(() => import('./dashboards/SalesAgentDashboard'));
export const SalesInsightsPage = lazy(() => import('./dashboards/SalesInsightsPage'));
export const SupportAgentDashboard = lazy(() => import('./dashboards/SupportAgentDashboard'));
export const SupervisorDashboard = lazy(() => import('./dashboards/SupervisorDashboard'));
